name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    uses: ./.github/workflows/build-windows-vst3.yml
    with:
      arch: x64
      run-pluginval: true

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Dependencies
      run: sudo bash scripts/install-linux-deps.sh
    - name: Configure CMake
      run: cmake --preset linux-release
    - name: Build
      run: cmake --build --preset linux-build
